#define lite           #151515

#define error          HSV 20 0.5 0.5
#define blue           #3047ba
#define green          #00ff00
#define red	           #ff0000
#define white          #ffffff
#define pink           #f080f0
#define yellow         #ffff00
#define black          #000000

#define grey1          #101010
#define grey3          #181818
#define grey4          #202020
#define grey7          #909090

#define fg_lite        #a0a0a0
#define fg_mid         #c0c0c0
#define fg_dim         #404040

#define main_sep       #2e2525
#define main_lo        #000000

#define separator      #505000

#define selected       #6060f0
#define unselected     #505080

#define hilite_blue    #c0c0ff

#define hilite_red     #ff80a0
#define hilite_dim_red #a070a0

#define mud_dim        #201b00
#define mud            #302b00
#define mud_lite       #605b00

#define mud_textbox    #201b00
#define mud_border_selected #c0a000
#define mud_hover_bg   #302b00

#define button_bg      #303000
#define button_fg      #605000

#define button_pressed_bg #505000
