#define lite                #151515

#define error               HSV 20 0.5 0.5
#define blue                #3047ba
#define green               #00ff00
#define red	                #ff0000
#define white               #ffffff
#define pink                #f080f0
#define yellow              #ffff00
#define black               #000000

#define grey1               #101010
#define grey3               #181818
#define grey4               #202020
#define grey7               #909090

#define fg_lite             #a0a0a0
#define fg_dim              #404040

#define separator           #3F4B61

#define selected            #6060f0
#define unselected          #505080

#define mud                 #302b00
#define mud_lite            #605b00
#define mud_hover_bg        #302b00

#define button_bg           #101010
#define button_bg_hi        #202020
#define button_fg           #505050

#define fg_blue             #505080
#define bg                  #0a1010

#define button_pressed_bg   #505000

#define border_selected     #ffc1c1

#define node_current        #00fa9a
#define node_selected       #8fbc8f
#define node_circle         #505050
#define node_flag           #302b00